---
- hosts: icarus
  sudo: yes
  roles:
    - rh-cacerts
    - icarus-system

- hosts: eventhorizon
  sudo: yes
  roles:
    - common
    - eventhorizon

- hosts: olympus
  sudo: yes
  roles:
    - atomichost
    - olympus

- hosts: icarus
  sudo: no
  roles:
    - common
    - icarus-walters

- hosts: escher
  sudo: yes
  roles:
    - atomichost
    - escher
