---
- hosts: icarus
  sudo: yes
  roles:
    - rh-cacerts
    - icarus-system

- hosts: eventhorizon
  sudo: yes
  roles:
    - common
    - eventhorizon

- hosts: icarus
  sudo: no
  roles:
    - common
    - icarus-walters
