---
- name: Development yum repositories
  action: copy src={{ item }}.repo dest=/etc/yum.repos.d/{{ item }}.repo
  with_items:
    - rhpkg

- yum: name={{ item }} state=present
  with_items:
    - emacs
    - keepassx
    - git
    - ansible
    - xchat
    - xsel
    - dnsmasq
    - virt-manager
    - virt-install
    - libguestfs-tools-c
    - python-novaclient
    - python-glanceclient
    - s3cmd
    - rhpkg
    - brewkoji
    - fedpkg
    - mock
    - createrepo_c
  tags:
    - packages

# nspawn is better, also https://lists.fedoraproject.org/pipermail/buildsys/2015-July/004833.html
- lineinfile: dest=/etc/mock/site-defaults.cfg line="config_opts['use_nspawn'] = True"
