---
- file: path=/etc/xdg/autostart/gnome-keyring-gpg.desktop state=absent

- yum: name={{ item }} state=present
  with_items:
    - pcsc-lite
    - gnupg2
    - gnupg2-smime
  tags:
    - packages

- service: name={{ item }} state=started enabled=true
  with_items:
    - pcscd.service
    - pcscd.socket
