---
- include: ../../common/tasks/gpg-system.yml
- include: gpg-smartcard.yml
- include: srv.yml
- include: pkgrepos.yml
- include: rhel-internal-yum-repos.yml
- include: ../../common/tasks/epel7.yml
- include: rdo-liberty.yml
- include: rhel-workstation-basesystem-packages.yml
- include: root-walters-homegit.yml
- include: ../../common/tasks/secure-shell-strong.yml
- include: libvirt.yml
- include: beaker-client.yml
- include: networkmanager-dnsmasq.yml
- include: devel-packages.yml
- include: docker.yml
- include: local-httpd-readonly.yml
- include: local-polipo.yml
