---
- name: vagrant-libvirt
  action: copy src={{ item }}.repo dest=/etc/yum.repos.d/{{ item }}.repo
  with_items:
    - jstribny-vagrant1-epel-7

- yum: name={{ item }} state=present
  with_items:
    - scl-utils
    - vagrant1-vagrant
  tags:
    - packages

 

