---
- include: ../../common/tasks/gpg-system.yml
- include: ../../common/tasks/secure-shell-strong.yml

- lineinfile: dest=/etc/systemd/journald.conf regexp='^[# ]*Storage=' line=Storage=volatile
  notify: reload journald

- file: path=/var/log/journal state=absent
