---
- name: stop docker
  service: name=docker state=stopped

- name: reload apache
  service: name=httpd state=reloaded

- name: reload systemd
  command: systemctl daemon-reload

- name: reload journald
  service: name=systemd-journald state=restarted
