---
# https://stribika.github.io/2015/01/04/secure-secure-shell.html
- name: Strong sshd server defaults
  action: lineinfile dest=/etc/ssh/sshd_config regexp=^{{ item.key }}  line="{{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'KexAlgorithms', value: 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256' }
    - { key: 'Ciphers', value: 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr' }
    - { key: 'MACs', value: 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com' }
  register: sshd

# And some tweaks for the default client configuration
- name: Disable ssh client GSSAPI auth, we enable only for specific hosts
  action: lineinfile dest=/etc/ssh/ssh_config regexp='GSSAPIAuthentication ' insertafter='^Host *' line='GSSAPIAuthentication no'

- name: Disable ssh client password auth, I use keys everywhere
  action: lineinfile dest=/etc/ssh/ssh_config regexp='PasswordAuthentication ' insertafter='^Host *' line='PasswordAuthentication no'

- name: Disable gnome-keyring ssh, as it doesn't support ed25519
  action: file dest=/etc/xdg/autostart/gnome-keyring-ssh.desktop state=absent



